### ISSUE TITLE
Allow for multiple providers for kernelspec-based kernels

### ISSUE THREAD

**Issue by kevin-bates** [takluyver/jupyter_kernel_mgmt#11]
Hi @takluyver.  I'd like to enable the ability to subclass `KernelSpecProvider` such that different kernel providers could still be based on kernelspecs yet have different launch and management capabilities.

The idea would be that non-default kernelspecs would include a `provider_id` indicator in the `metadata` of the `kernel.json` file.  This indicator would match that of the provider performing the search.  `kernel.json` files with no such entry or an entry = `'spec'` would be handled by `KernelSpecProvider`.

To better accomplish this, it would good to merge `KernelSpecProvider` with `KernelSpecManager`.  Is there a reason these are different - other than ease of initial POC?  Otherwise, conveyance of `self.id` is a bit of a hassle and in makes sense (IMO) to have this functionality isolated in the provider.

Each of the subclasses of `KernelSpecProvider` then have the option of implementing their own `launch()` methods, etc. but the search for kernelspecs could then all be shared.

Since 100% of kernel launches today are based on kernelspecs, applications/features wishing to leverage 'provider-type' functionality - while still adhering to kernelspec as a foundation could be implemented.

I am happy to perform the merge/reorganization, but would like your input/opinion prior to spending time on this.

**Comment by takluyver** [comment]
Yes, I think given the historic constraints it makes sense to have some way of marking kernelspecs so that they're ignored by the default provider. At the same time, I would be clear that new providers probably don't want to be looking for kernelspecs - the providers mechanism is meant to supersede kernelspecs, not to entrench them.

Providers and managers are quite different things, and I wouldn't merge them:

- Managers have a 1:1 relationship with running kernel instances, whereas one provider can launch many kernel instances.
- Different providers can use the same manager class - e.g. a provider which finds kernels in conda envs would probably share the 'subprocess' manager which the 'spec' provider also uses. Composing these as separate classes seems neater than doing multiple inheritance for them.

I don't really have the time to drive my design further, though. You've already made APIs doing a lot of the same things and used them in real-world situations, so you don't have to convince me - you can take anything that's useful from my experiments and use it as seems best.

**Comment by kevin-bates** [comment]
Thanks for response Thomas.  The _merge_ I'm talking about doing is the Kernel**Spec**Manager, not KernelManager.  I would like to merge `KernelSpecManager` into `KernelSpecProvider`.

Yes, I'm finding the all of my providers use the same (remote) kernel manager.

**Comment by takluyver** [comment]
Oh,  sorry, my mistake. That makes more sense. Maybe I was leaving it in case existing third-party code was using `KernelSpecManager`. But probably this suite of changes would break any such code anyway.

**Comment by kevin-bates** [comment]
Yeah, I was thinking that might be why, but also agree changes would likely be required anyway.  That said, I will try to keep signatures the same (easier since self.id will be available) so as to minimize any tooling that might leverage these functions.
